apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loop-sequence-
  namespace: argo
spec:
  entrypoint: loop-sequence-example
  serviceAccountName: training

  templates:
  - name: loop-sequence-example
    steps:
    - - name: hello-world-x5
        template: hello-world
        withSequence:
          count: "5"

  - name: hello-world
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world!"]
