apiVersion: v1
kind: Service
metadata:
  name: argo-server-nodeport
  namespace: argo
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - protocol: TCP
      port: 2746
      targetPort: 2746
      nodePort: 30000 # Specify the nodePort value you want to use
