apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: diamond-example-training
  namespace: argo
spec:
  serviceAccountName: training
  entrypoint: diamond
  templates:
    - name: diamond
      dag:
        tasks:
          - name: A
            template: echo
          - name: B
            dependencies: [A]
            template: echo
          - name: C
            dependencies: [A]
            template: echo
          - name: D
            dependencies: [B, C]
            template: echo
    - name: echo
      container:
        image: busybox
        command: [echo, "Task executed."]
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
